"""
Core scheduling engine for the Couple Scheduler.
Responsible for aggregating all temporal constraints (work, sleep, fixed appointments, trips)
and feeding them to the Gemini LLM to generate an optimized week plan.
"""

from google import genai
from backend.database import get_db, get_setting
import json
import uuid
from datetime import datetime, timedelta

def generate_schedule(start_date: str, end_date: str):
    """
    Retrieves all user constraints for a specific date range and prompts the AI to generate an optimized schedule.
    This function acts as the central brain of the application, orchestrating raw constraints into a unified timeline.
    
    Why:
    - Filters are applied strictly to the start/end date window to minimize token usage and prevent context overflow in the LLM.
    - Trips are injected as highest-priority blocks, actively overriding goals and projects to ensure vacations aren't polluted by mundane habits.
    
    Args:
        start_date (str): The ISO string (YYYY-MM-DD) representing Monday.
        end_date (str): The ISO string (YYYY-MM-DD) representing Sunday.
        
    Returns:
        dict: The raw JSON schedule generated by Gemini and inserted into the database.
    """
    gemini_api_key = get_setting("gemini_api_key")
    if not gemini_api_key:
        raise Exception("Gemini API Key is not configured.")
        
    client = genai.Client(api_key=gemini_api_key)
    
    with get_db() as conn:
        cursor = conn.cursor()
        
        # Filter commitments by the target schedule window to save tokens
        cursor.execute("SELECT * FROM commitments WHERE (start_time IS NULL OR start_time <= ?) AND (end_time IS NULL OR end_time >= ?)", (end_date + "T23:59:59", start_date + "T00:00:00"))
        commitments = [dict(row) for row in cursor.fetchall()]
        
        cursor.execute("SELECT * FROM goals")
        all_goals = [dict(row) for row in cursor.fetchall()]
        
        cursor.execute("SELECT * FROM projects")
        all_projects = [dict(row) for row in cursor.fetchall()]
        
        cursor.execute("SELECT * FROM work_shifts WHERE date >= ? AND date <= ?", (start_date, end_date))
        work_shifts = [dict(row) for row in cursor.fetchall()]
        
        cursor.execute("SELECT * FROM sleep_schedules")
        sleep_schedules = [dict(row) for row in cursor.fetchall()]

        # Exemptions
        cursor.execute("SELECT * FROM exemptions")
        exemptions = [dict(row) for row in cursor.fetchall()]

        # Trips hook: fetch planned or scheduled trips overlapping this week
        cursor.execute('''
            SELECT * FROM trips 
            WHERE status IN ('planned', 'scheduled') 
            AND start_date <= ? AND end_date >= ?
        ''', (end_date, start_date))
        overlapping_trips = [dict(row) for row in cursor.fetchall()]

    schedule_start_dt = datetime.strptime(start_date, "%Y-%m-%d")
    current_week_str = start_date # Since start_date is Monday

    # If there's an overlapping trip, block out goals and projects, and inject the trip as a commitment
    if overlapping_trips:
        all_goals = []
        all_projects = []
        for t in overlapping_trips:
            commitments.append({
                'title': f"TRIP: {t['destination']}",
                'start_time': f"{t['start_date']}T00:00:00",
                'end_time': f"{t['end_date']}T23:59:59",
                'is_fixed': True,
                'user_id': 'both'
            })

    # Process goals for ramp-up and exemptions
    processed_goals = []
    for g in all_goals:
        if any(ex["item_id"] == g["id"] and ex["skip_week_start"] == current_week_str for ex in exemptions):
            continue
            
        goal_start_str = g.get('start_date')
        target = g['target_per_week']
        if goal_start_str:
            try:
                goal_start_dt = datetime.strptime(goal_start_str, "%Y-%m-%d")
                weeks_since_start = max(0, (schedule_start_dt - goal_start_dt).days // 7)
                ramp_offset = g.get('ramp_offset', 0) or 0
                effective_week = max(1, weeks_since_start - ramp_offset + 1)
                target = min(effective_week, g['target_per_week'])
            except:
                pass
        
        pg = dict(g)
        pg['target_per_week'] = target
        processed_goals.append(pg)

    # Process projects for 4-hour blocks and exemptions
    processed_projects = []
    for p in all_projects:
        if any(ex["item_id"] == p["id"] and ex["skip_week_start"] == current_week_str for ex in exemptions):
            continue
            
        pp = dict(p)
        pp['instruction'] = "Break this project up into multiple blocks of no more than 4 hours each. Schedule the necessary 4-hour blocks over the week to make progress towards the total hours."
        processed_projects.append(pp)

    settings = {
        "user1": {
            "name": get_setting("user1_name", "User 1")
        },
        "user2": {
            "name": get_setting("user2_name", "User 2")
        }
    }
    
    prompt = f"""
You are an expert AI scheduler for a couple. You need to generate a schedule from {start_date} to {end_date}.
The system tracks two distinct users: user1 and user2. 

Here is their configuration:
Settings: {json.dumps(settings)}

Here are their data items (each item has a 'user_id' indicating who it belongs to):
Specific Work Shifts: {json.dumps(work_shifts)}
Sleep Schedules (rules defining intended sleep hours): {json.dumps(sleep_schedules)}
Fixed Commitments: {json.dumps(commitments)}
Flexible Goals (need to be scheduled during free time): {json.dumps(processed_goals)}
Active Projects (schedule time to work on them): {json.dumps(processed_projects)}

Rules:
1. Schedule blocks for BOTH users in the SAME schedule.
2. CRITICAL: For each user, block out their specific sleep hours and work hours FIRST based ONLY on the provided Specific Work Shifts and Sleep Schedules. DO NOT schedule work if there is no shift for that day. Label these with their user_id.
3. CRITICAL: Block out Fixed Commitments for the respective user exactly as provided in the data.
4. AGGRESSIVELY IDENTIFY ALL REMAINING FREE TIME: After blocking out sleep, work, and commitments, you MUST explicitly identify all remaining free time windows for each day (e.g., if work ends at 17:30 and sleep begins at 23:00, you have a 5.5 hour free time window to fill).
5. Fit flexible goals (e.g., workouts, reading) into these free time slots based on their weekly target and duration. Do not leave large gaps of free time unscheduled if there are goals or projects remaining.
6. Allocate time for active projects within these free time slots. Pay attention to the "instruction" field to break them into blocks (up to 4 hours each) to aggressively make progress towards the total hours.
7. A slot can belong to "user1", "user2", or "both" (if it's a shared activity like sleeping at the same time, or overlapping free time).
8. Return a JSON object with this exact schema (no markdown, just JSON):
{{
  "days": {{
    "YYYY-MM-DD": [
      {{ 
        "start_time": "HH:MM", 
        "end_time": "HH:MM", 
        "title": "String", 
        "type": "sleep|work|commitment|goal|project|free",
        "user_id": "user1|user2|both",
        "item_id": "String (the UUID of the item from the provided data, or null)"
      }}
    ]
  }},
  "warnings": ["String array of scheduling conflicts or missed targets, if any"]
}}
"""

    response = client.models.generate_content(
        model='gemini-3.5-flash',
        contents=prompt,
        config=genai.types.GenerateContentConfig()
    )
    
    raw_response = response.text.strip()
    if raw_response.startswith("```json"):
        raw_response = raw_response[7:-3]
    elif raw_response.startswith("```"):
        raw_response = raw_response.split("\n", 1)[1].rsplit("```", 1)[0].strip()
        
    parsed_schedule = json.loads(raw_response)
    
    with get_db() as conn:
        cursor = conn.cursor()
        schedule_id = str(uuid.uuid4())
        cursor.execute(
            "INSERT INTO schedules (id, start_date, end_date, schedule_json) VALUES (?, ?, ?, ?)",
            (schedule_id, start_date, end_date, json.dumps(parsed_schedule))
        )
        conn.commit()
        
    return parsed_schedule
